site_name: RingCentral Web Widget Demos
site_url: https://github.com/ringcentral-tutorials/ringcentral-web-widget-demos
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral-tutorials/ringcentral-web-widget-demos.git
docs_dir: docs
theme: readthedocs
extra_css: [assets/extra.css]
extra_javascript: [assets/fonts.js]
pages:
- 'Overview': 'index.md'
- 'Static Simple Demo': 'static_simple/tutorial/index.md'
- 'Static CRM Demo': 'static_crm/tutorial/index.md'
- 'Salesforce Lightning Demo': 'salesforce_lightning/tutorial/index.md'
- 'More Salesforce Lightning': 'salesforce_lightning_more/tutorial/index.md'
- 'Java Desktop App Demo': 'java_desktop_app/tutorial/index.md'
